# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class ChaosLab < Formula
  desc "Polyglot chaos orchestrator — scenarios in any language, one CLI/TUI"
  homepage "https://github.com/pinpredict/chaos-lab"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinpredict/chaos-lab/releases/download/v0.0.0/chaos-lab_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f5c3285061aff1992ce9eece0461ddfd764fa95adfa6df6bf463639d9d086c38"

      define_method(:install) do
        bin.install "chaos-lab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinpredict/chaos-lab/releases/download/v0.0.0/chaos-lab_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "199be2f90d19a6adeba0019666d09a6097f3e5f03b498aae82acda93dd461459"

      define_method(:install) do
        bin.install "chaos-lab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/chaos-lab/releases/download/v0.0.0/chaos-lab_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "05374f1c0a917380a7e5b0c37b6de2541dee91372a0fc30b23a80acb05ca7d0d"
      define_method(:install) do
        bin.install "chaos-lab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/chaos-lab/releases/download/v0.0.0/chaos-lab_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2c7d35ad0c3cb996a516dde4c91352d602d37d11f9dd2b05ae59bcefa092744d"
      define_method(:install) do
        bin.install "chaos-lab"
      end
    end
  end

  test do
    system "#{bin}/chaos-lab", "version"
  end
end
