# typed: false
# frozen_string_literal: true

require_relative "../lib/custom_download_strategy"

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudctl < Formula
  desc "Declarative IaC CLI for multi-cloud account management"
  homepage "https://github.com/pinpredict/cloudctl"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinpredict/cloudctl/releases/download/v0.1.1/cloudctl_Darwin_x86_64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "928f1dbe3df2fda6d7c229ceeedead6e05a758799f6e723ede51668d38395f20"

      define_method(:install) do
        bin.install "cloudctl"
        bin.install "aws-provider"
        bin.install "azure-provider"
        bin.install "terraform-generator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinpredict/cloudctl/releases/download/v0.1.1/cloudctl_Darwin_arm64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b1cc39144b975ad991b666596946b45a6acd746e0f09f4265a54fdbb5168ca91"

      define_method(:install) do
        bin.install "cloudctl"
        bin.install "aws-provider"
        bin.install "azure-provider"
        bin.install "terraform-generator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/cloudctl/releases/download/v0.1.1/cloudctl_Linux_x86_64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "650c171a228935483ab4d674efd53f405aaaa99821007fcaa105e8cd72546798"
      define_method(:install) do
        bin.install "cloudctl"
        bin.install "aws-provider"
        bin.install "azure-provider"
        bin.install "terraform-generator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/cloudctl/releases/download/v0.1.1/cloudctl_Linux_arm64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "93757be8d7361145d674c9de553a8576f8f1ce307379f3907baa61136521aec2"
      define_method(:install) do
        bin.install "cloudctl"
        bin.install "aws-provider"
        bin.install "azure-provider"
        bin.install "terraform-generator"
      end
    end
  end

  test do
    system "#{bin}/cloudctl", "version"
  end
end
