# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cwlogs < Formula
  desc "Tail AWS CloudWatch container logs with colorized output"
  homepage "https://github.com/pinpredict/cwlogs"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinpredict/cwlogs/releases/download/v0.0.2/cwlogs_Darwin_x86_64.tar.gz"
      sha256 "fd190f46aa5f21a2a2a0d7bcd57e1c42e5b70f537862022c46e98564b7bdc1ee"

      define_method(:install) do
        bin.install "cwlogs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinpredict/cwlogs/releases/download/v0.0.2/cwlogs_Darwin_arm64.tar.gz"
      sha256 "884944a7f1db881dc868d31b9429489fc12cea163bf107f9ee5481d0d9d49de1"

      define_method(:install) do
        bin.install "cwlogs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/cwlogs/releases/download/v0.0.2/cwlogs_Linux_x86_64.tar.gz"
      sha256 "eaadc7422be3fca54f5149d34577a42859649fc36e2dff6ede39e08e6bd615b5"
      define_method(:install) do
        bin.install "cwlogs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/cwlogs/releases/download/v0.0.2/cwlogs_Linux_arm64.tar.gz"
      sha256 "d0f003b0959ce2aeba96b4dd3baa4dedc3c6565ad65e165a2eeb0794200b1292"
      define_method(:install) do
        bin.install "cwlogs"
      end
    end
  end

  test do
    system "#{bin}/cwlogs", "version"
  end
end
