# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Cwlogs < Formula
  desc "Tail AWS CloudWatch container logs with colorized output"
  homepage "https://github.com/pinpredict/cwlogs"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinpredict/cwlogs/releases/download/v0.0.3/cwlogs_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "516ea5719f61bc6ba5b597dbe33c3343cf56e96075a01bc0c43bcbfd6b02867e"

      define_method(:install) do
        bin.install "cwlogs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinpredict/cwlogs/releases/download/v0.0.3/cwlogs_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b7f718d4b6ef7e4f491f3da0351d29be624a55d78d7b840e2c3bdced9ed02d64"

      define_method(:install) do
        bin.install "cwlogs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/cwlogs/releases/download/v0.0.3/cwlogs_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cc3d0eb3fb470c18dcd4911a925de017778337fda9a7484f11301a61f3fe2de5"
      define_method(:install) do
        bin.install "cwlogs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/cwlogs/releases/download/v0.0.3/cwlogs_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "89e55ca66db670bfd6f1d79ef8c9fda08f269a3dd4eb1698a154690f94d4d1ea"
      define_method(:install) do
        bin.install "cwlogs"
      end
    end
  end

  test do
    system "#{bin}/cwlogs", "version"
  end
end
