# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class K5 < Formula
  desc "Kubernetes dev environments + polyglot chaos verification — one CLI/TUI"
  homepage "https://github.com/pinpredict/k5s"
  version "0.0.84"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.84/k5_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "20d7409b82e545e9279dfb2929e64e374c36c734aa4b8a8fb1970e70070574d8"

      define_method(:install) do
        bin.install "k5", "exec-scenario"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.84/k5_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c73a0336c24aabb070a8f587eedf9cee8e852c700c0e5675c7e59b3b10b87dc0"

      define_method(:install) do
        bin.install "k5", "exec-scenario"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.84/k5_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2b3e45082f6d3003b528be49eace2f8b1cb82b62a70206c5df3054e61230987c"
      define_method(:install) do
        bin.install "k5", "exec-scenario"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.84/k5_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1a7c2c6fba5e361a01959825a2f1d1c5bcf3bb6a9712c24d23a47fbd7877ec24"
      define_method(:install) do
        bin.install "k5", "exec-scenario"
      end
    end
  end

  test do
    system "#{bin}/k5", "version"
    assert_predicate bin/"exec-scenario", :executable?
  end
end
