# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class K5s < Formula
  desc "Kubernetes dev environments + polyglot chaos verification — one CLI/TUI"
  homepage "https://github.com/pinpredict/k5s"
  version "0.0.37"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.37/k5s_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "574832ec69870edbf865e7bb0d451e91fda3a7b84f1a99b5746f6b6dd85ce760"

      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.37/k5s_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6f011632f4afd252e0528bf92d6cedc91cf64ff19374d9cfeac0cf77b229c186"

      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.37/k5s_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5f4899607ea5d2ab2283abee189f38ae481b274069175698d9cbbd60c2cc040d"
      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.37/k5s_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9532b9121143c397a0f4ed6da76f055261ff8e9b6a85fdd0cef79a1462c9fd25"
      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
  end

  test do
    system "#{bin}/k5s", "version"
    assert_predicate bin/"exec-scenario", :executable?
  end
end
