# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class K5s < Formula
  desc "Kubernetes dev environments + polyglot chaos verification — one CLI/TUI"
  homepage "https://github.com/pinpredict/k5s"
  version "0.0.48"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.48/k5s_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "83d4feb3af93a51a31da95376b6cfca4a4cff02279b25335d6a9fdc571a06f2b"

      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.48/k5s_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7bb0e112a4e7a5ab5c7909868c978df3b393e5c6fd32ec0f6fd38fbe867f43f9"

      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.48/k5s_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "db9e72d9035ee7e991bd386e9646149a21fbc5bae0996138e4d9bc7ded1ee745"
      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.48/k5s_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "296b9e5ebc0d1106efbe98c0bd58df7d736cbdebebbd31c25e9ddf1a65e69e34"
      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
  end

  test do
    system "#{bin}/k5s", "version"
    assert_predicate bin/"exec-scenario", :executable?
  end
end
