# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class K5s < Formula
  desc "Kubernetes dev environments + polyglot chaos verification — one CLI/TUI"
  homepage "https://github.com/pinpredict/k5s"
  version "0.0.56"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.56/k5s_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "49b8429060207d401ccb366a4ad46094df48cd430ed3cea9db2a33b2d882792b"

      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.56/k5s_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f476091b402e3af80b892cbac5c61155a1363b9ffd397e17da894b1d5f170852"

      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.56/k5s_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "32d28145d4930b68d2b5eb2fedaac3413f0b9d8abf67451d053d921b01a14d05"
      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/k5s/releases/download/v0.0.56/k5s_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f1c396da468fe97a5545742ca61c174dd321689778444e7fed334582296bb674"
      define_method(:install) do
        bin.install "k5s", "exec-scenario"
      end
    end
  end

  test do
    system "#{bin}/k5s", "version"
    assert_predicate bin/"exec-scenario", :executable?
  end
end
