# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class PpTui < Formula
  desc "Read-only TUI for watching PinPredict trading activity in real time"
  homepage "https://github.com/pinpredict/pp-tui"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinpredict/pp-tui/releases/download/v0.0.0/pp-tui_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a7a13d91757e6e8c7322c5f7063bec94121753277e67d55ed654dd6dc6defe33"

      define_method(:install) do
        bin.install "pp-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinpredict/pp-tui/releases/download/v0.0.0/pp-tui_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a32d20d4b3a65b5088db1137e5168eca74b895b4b1e33aa94d163a4653a4a8fc"

      define_method(:install) do
        bin.install "pp-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/pp-tui/releases/download/v0.0.0/pp-tui_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bf0f9dd4f6fb0d3e28f6ccdf663640504f98480249105f14e3fb73661cba62da"
      define_method(:install) do
        bin.install "pp-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinpredict/pp-tui/releases/download/v0.0.0/pp-tui_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dbc8f3d7077afe1fd3ee3c7bfced428bf9773f1063239ba082b55bc6447c6807"
      define_method(:install) do
        bin.install "pp-tui"
      end
    end
  end

  test do
    system "#{bin}/pp-tui", "--version"
  end
end
